### ISSUE TITLE
Modifications for partial sky

### ISSUE THREAD

**Issue by bthorne93** [bthorne93/PySM_public#10]
@zonca  These are the changes I think will need to be made to allow the code to consider only partial maps. Most likely an incomplete list, but I hope it helps! Thanks so much! 

- **Initialization**: 
  - Any use of the code is initialized using the `models` function in `nominal.py`. I imagine just adding a kwarg for `pixel_indices` to that would be the thing to do.
- **Inputs**:
  - Input templates are read-in in `nominal.py`. Modifying the `models` function in this file will do a lot of the work.
- **Processing**: Several models generate maps of random values on the fly (e.g. CMB, HD17). These will need to be checked to make sure they are either generated for the required number of pixels when possible, or for the whole sky and then reduced for e.g. the CMB.
  - `components.py`:
    - `CMB` class, `taylens` function.
    - `Dust` class, `hensley_draine_2017` function through the `draw_uval` function, which draws a map of random values. Unfortunately, due to a work around we had to use in order to speed it up this model also relies on the `initialise_hd_dust_model_bandpass` function in `pysm.py`, which initializes the model when bandpass-integration is requested.
  - `instrument.py`:
    - `noiser` method of `instrument` class.
- **Outputs**:
  - Maps are only saved to file when the `Instrument.observe` is used on an instance of the `Sky` object. So `Instrument.writer` will have to be able to pad the chosen pixels with zeros when doing only partial skies.

**Comment by zonca** [comment]
thanks @bthorne93 I started working on this, I'm checking the other functions to make sure they don't need to be modified.

I'm checking `decorrelation` in `components.py`, I believe it doesn't need modifications, right?

**Comment by bthorne93** [comment]
@zonca The current decorrelation model is meant to just multiply by a scalar at each frequency, so in theory it shouldn't need to be modified.

**Comment by zonca** [comment]
I think we can close this issue, this has been merged in #11
