### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by zonca** [bthorne93/PySM_public#19]
As there are no current Pull Requests open I think it would be a good time to tag a release on Github, maybe `2.1.0` (as I think the first version of this new codebase was tagged 2.0).

It would be useful for our work on TOAST so we can install a specific release.

See https://help.github.com/articles/creating-releases/

**Comment by bthorne93** [comment]
Version 2.1.0 has now been tagged!

**Comment by zonca** [comment]
Thanks!

**Comment by bthorne93** [comment]
Of course! Apologies for the delay.
