### ISSUE TITLE
How to calculate the E and B mode signal from Q and U map?

### ISSUE THREAD

**Issue by YJHelloWorld** [bthorne93/PySM_public#27]
Hi, I am wondering if there is a method to calculate the E and B mode signal from Q and U map in the pysm?

**Comment by dpole** [comment]
Hi, I think that the tools you are looking for are in [healpy](https://healpy.readthedocs.io/en/latest/#). If by signal you mean the EE and BB power spectrum, `healpy.anafast` is what you need.

**Comment by YJHelloWorld** [comment]
Oh, I got it. Thank you so much.
