### ISSUE TITLE
Dust temperature can't be scalar

### ISSUE THREAD

**Issue by susannaaz** [bthorne93/PySM_public#35]
Cell 13 in the example notebook (https://github.com/bthorne93/PySM_public/blob/master/example.ipynb) seems to suggest that one could make all spectral parameters of a given component scalars instead of maps. This however seems to work only for spectral indices, not for e.g. dust temperature (the code will crash if you replace 'spectral_index' with 'temp' in that same cell)

I also think some aspects of the example notebooks are outdated (e.g. bare 'print' statements a la python2.7)

**Comment by zonca** [comment]
thanks for your feedback.
yes, correct, you need to create an array.
we are focusing now on the development of PySM 3, still work in progress at https://github.com/healpy/pysm
so won't develop any improvements on PySM 2, just bugfixes.
as for the print statement, if you want to provide a pull request, I'll be happy to merge it.
